# Generated by Django 3.2.19 on 2023-06-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
